# Generated by Django 2.2.6 on 2019-10-26 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCategorie', models.CharField(max_length=20)),
                ('descriptionCategorie', models.CharField(max_length=10)),
                ('imageCategorie', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Louma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=19)),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('Samdi', 'Samdi'), ('Dimanche', 'Dimanche')], default='Lundi', max_length=10)),
                ('zone', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='zone', to='TestApp.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Crée le')),
                ('lastmodified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Dernière modification')),
                ('nom', models.CharField(max_length=19)),
                ('prix', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriearticle', to='TestApp.Categorie')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testapp_articles_created', to=settings.AUTH_USER_MODEL, verbose_name='Ajoute Par')),
                ('lastmodified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testapp_articles_lastmodified', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('louma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='TestApp.Louma')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
